import AppKit

/// Reads and writes the general pasteboard for the clipboard history.
@MainActor
protocol ClipboardAccessing: AnyObject {
    var changeCount: Int { get }
    /// The current pasteboard item, or `nil` when it is empty, private
    /// (password managers mark those) or of an unsupported type.
    func currentEntry() -> ClipboardEntry?
    /// Puts an entry back on the pasteboard; returns the new change count.
    @discardableResult
    func write(_ entry: ClipboardEntry) -> Int
}

@MainActor
final class ClipboardHistoryService: ClipboardAccessing {
    private let pasteboard: NSPasteboard

    /// Markers from nspasteboard.org that apps set on secrets and throwaway data.
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]
    /// Longer text is still kept but trimmed, so a huge copy can't bloat memory.
    private static let maxTextLength = 20_000

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    var changeCount: Int {
        pasteboard.changeCount
    }

    func currentEntry() -> ClipboardEntry? {
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty, types.isDisjoint(with: Self.ignoredTypes) else { return nil }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipboardEntry(content: .files(urls), copiedAt: Date(), sourceBundleIdentifier: source)
        }

        // Prefer text over images: rich text copies often carry a preview image too.
        if let text = pasteboard.string(forType: .string) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }

            if let url = URL(string: trimmed), let scheme = url.scheme, ["http", "https"].contains(scheme),
               !trimmed.contains(where: \.isWhitespace) {
                return ClipboardEntry(content: .url(url), copiedAt: Date(), sourceBundleIdentifier: source)
            }

            return ClipboardEntry(
                content: .text(String(text.prefix(Self.maxTextLength))),
                copiedAt: Date(),
                sourceBundleIdentifier: source
            )
        }

        if let image = NSImage(pasteboard: pasteboard) {
            return ClipboardEntry(content: .image(image), copiedAt: Date(), sourceBundleIdentifier: source)
        }

        return nil
    }

    @discardableResult
    func write(_ entry: ClipboardEntry) -> Int {
        pasteboard.clearContents()

        switch entry.content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .url(let url):
            pasteboard.writeObjects([url as NSURL])
            pasteboard.setString(url.absoluteString, forType: .string)
        case .files(let urls):
            pasteboard.writeObjects(urls.map { $0 as NSURL })
        case .image(let image):
            pasteboard.writeObjects([image])
        }

        return pasteboard.changeCount
    }
}
